version: "3.8"
services:
  portainer:
    image: portainer/portainer-ce:latest
    ports:
      - 9443:9000
      - 8443:8000
    volumes:
      - /portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always





# docker run -d -p 9443:9000 -p 8443:8000 --name portainer --restart always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest
